name: "firebot v5 lint"

on:
  push:
    branches:
      - v5

jobs:
  test:
    name: "Lint"
    runs-on: "windows-latest"
    steps:
      # clone the repo v5 branch
      - uses: "actions/checkout@v1"
        with:
          fetch-depth: 1
          
      # install nodejs and npm
      - uses: "actions/setup-node@v1"
        with:
          node-version: "12.14.1"

      # install eslint
      - run: "npm install eslint@5.16.0"
        
      # run linter
      - run: "npm run lint"
